///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace AutomationSQLdm
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the AutomationSQLdmRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
    [RepositoryFolder("7bd21acd-09e4-4c42-81c5-68b39ccd889b")]
    public partial class AutomationSQLdmRepository : RepoGenBaseFolder
    {
        static AutomationSQLdmRepository instance = new AutomationSQLdmRepository();
        AutomationSQLdmRepositoryFolders.ExplorerAppFolder _explorer;
        AutomationSQLdmRepositoryFolders.NotificationRulesDialogAppFolder _notificationrulesdialog;
        AutomationSQLdmRepositoryFolders.AddActionProviderWizardAppFolder _addactionproviderwizard;
        AutomationSQLdmRepositoryFolders.SQLdmDesktopClientAppFolder _sqldmdesktopclient;
        AutomationSQLdmRepositoryFolders.IderaSQLDiagnosticManagerSQLdmRepoAppFolder _iderasqldiagnosticmanagersqldmrepo;
        AutomationSQLdmRepositoryFolders.ExceptionMessageBoxFormAppFolder _exceptionmessageboxform;

        /// <summary>
        /// Gets the singleton class instance representing the AutomationSQLdmRepository element repository.
        /// </summary>
        [RepositoryFolder("7bd21acd-09e4-4c42-81c5-68b39ccd889b")]
        public static AutomationSQLdmRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public AutomationSQLdmRepository() 
            : base("AutomationSQLdmRepository", "/", null, 0, false, "7bd21acd-09e4-4c42-81c5-68b39ccd889b", ".\\RepositoryImages\\AutomationSQLdmRepository7bd21acd.rximgres")
        {
            _explorer = new AutomationSQLdmRepositoryFolders.ExplorerAppFolder(this);
            _notificationrulesdialog = new AutomationSQLdmRepositoryFolders.NotificationRulesDialogAppFolder(this);
            _addactionproviderwizard = new AutomationSQLdmRepositoryFolders.AddActionProviderWizardAppFolder(this);
            _sqldmdesktopclient = new AutomationSQLdmRepositoryFolders.SQLdmDesktopClientAppFolder(this);
            _iderasqldiagnosticmanagersqldmrepo = new AutomationSQLdmRepositoryFolders.IderaSQLDiagnosticManagerSQLdmRepoAppFolder(this);
            _exceptionmessageboxform = new AutomationSQLdmRepositoryFolders.ExceptionMessageBoxFormAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("7bd21acd-09e4-4c42-81c5-68b39ccd889b")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The Explorer folder.
        /// </summary>
        [RepositoryFolder("d6660ebb-ca52-45a1-8dce-4d22c397e3cd")]
        public virtual AutomationSQLdmRepositoryFolders.ExplorerAppFolder Explorer
        {
            get { return _explorer; }
        }

        /// <summary>
        /// The NotificationRulesDialog folder.
        /// </summary>
        [RepositoryFolder("9f200de9-8797-48ef-9f27-56aeb7132e21")]
        public virtual AutomationSQLdmRepositoryFolders.NotificationRulesDialogAppFolder NotificationRulesDialog
        {
            get { return _notificationrulesdialog; }
        }

        /// <summary>
        /// The AddActionProviderWizard folder.
        /// </summary>
        [RepositoryFolder("1f8437ee-6cf0-4549-a719-df087fa545cf")]
        public virtual AutomationSQLdmRepositoryFolders.AddActionProviderWizardAppFolder AddActionProviderWizard
        {
            get { return _addactionproviderwizard; }
        }

        /// <summary>
        /// The SQLdmDesktopClient folder.
        /// </summary>
        [RepositoryFolder("19f8a4a0-de98-4d04-8302-0fd75c348780")]
        public virtual AutomationSQLdmRepositoryFolders.SQLdmDesktopClientAppFolder SQLdmDesktopClient
        {
            get { return _sqldmdesktopclient; }
        }

        /// <summary>
        /// The IderaSQLDiagnosticManagerSQLdmRepo folder.
        /// </summary>
        [RepositoryFolder("02e2bddb-96ad-4da9-bf49-406cf03d0b37")]
        public virtual AutomationSQLdmRepositoryFolders.IderaSQLDiagnosticManagerSQLdmRepoAppFolder IderaSQLDiagnosticManagerSQLdmRepo
        {
            get { return _iderasqldiagnosticmanagersqldmrepo; }
        }

        /// <summary>
        /// The ExceptionMessageBoxForm folder.
        /// </summary>
        [RepositoryFolder("a6f6ed3c-e133-491f-83e7-43a77aec91a2")]
        public virtual AutomationSQLdmRepositoryFolders.ExceptionMessageBoxFormAppFolder ExceptionMessageBoxForm
        {
            get { return _exceptionmessageboxform; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", "8.2")]
    public partial class AutomationSQLdmRepositoryFolders
    {
        /// <summary>
        /// The ExplorerAppFolder folder.
        /// </summary>
        [RepositoryFolder("d6660ebb-ca52-45a1-8dce-4d22c397e3cd")]
        public partial class ExplorerAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _iderasqldiagnosticmanagersqldmrepoInfo;

            /// <summary>
            /// Creates a new Explorer  folder.
            /// </summary>
            public ExplorerAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Explorer", "/menubar[@processname='explorer']", parentFolder, 30000, null, true, "d6660ebb-ca52-45a1-8dce-4d22c397e3cd", "")
            {
                _iderasqldiagnosticmanagersqldmrepoInfo = new RepoItemInfo(this, "IderaSQLDiagnosticManagerSQLdmRepo", "container[@controlid='40965']//toolbar[@accessiblename='Running applications']/button[@accessiblename~'^Idera\\ SQL\\ diagnostic\\ mana']", 30000, null, "56f9c558-818b-4a55-be02-8a090a6a632c");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("d6660ebb-ca52-45a1-8dce-4d22c397e3cd")]
            public virtual Ranorex.MenuBar Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.MenuBar>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("d6660ebb-ca52-45a1-8dce-4d22c397e3cd")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The IderaSQLDiagnosticManagerSQLdmRepo item.
            /// </summary>
            [RepositoryItem("56f9c558-818b-4a55-be02-8a090a6a632c")]
            public virtual Ranorex.Button IderaSQLDiagnosticManagerSQLdmRepo
            {
                get
                {
                    return _iderasqldiagnosticmanagersqldmrepoInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The IderaSQLDiagnosticManagerSQLdmRepo item info.
            /// </summary>
            [RepositoryItemInfo("56f9c558-818b-4a55-be02-8a090a6a632c")]
            public virtual RepoItemInfo IderaSQLDiagnosticManagerSQLdmRepoInfo
            {
                get
                {
                    return _iderasqldiagnosticmanagersqldmrepoInfo;
                }
            }
        }

        /// <summary>
        /// The NotificationRulesDialogAppFolder folder.
        /// </summary>
        [RepositoryFolder("9f200de9-8797-48ef-9f27-56aeb7132e21")]
        public partial class NotificationRulesDialogAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _actionprovidersInfo;
            RepoItemInfo _addbuttonInfo;
            RepoItemInfo _removebuttonInfo;
            RepoItemInfo _cancelbuttonInfo;

            /// <summary>
            /// Creates a new NotificationRulesDialog  folder.
            /// </summary>
            public NotificationRulesDialogAppFolder(RepoGenBaseFolder parentFolder) :
                    base("NotificationRulesDialog", "/form[@controlname='NotificationRulesDialog']", parentFolder, 30000, null, true, "9f200de9-8797-48ef-9f27-56aeb7132e21", "")
            {
                _actionprovidersInfo = new RepoItemInfo(this, "ActionProviders", "element[@controlname='ultraTabControl1']/?/?/tabpage[@accessiblename='Action Providers']", 30000, null, "59284170-fbf3-4877-b284-4500d8843760");
                _addbuttonInfo = new RepoItemInfo(this, "AddButton", "?/?/container[@controlname='ultraTabPageControl2']//container[@controlname='panel1']/button[@controlname='addButton']", 30000, null, "966da63c-aba5-403e-8334-8189cf434ae1");
                _removebuttonInfo = new RepoItemInfo(this, "RemoveButton", "?/?/container[@controlname='ultraTabPageControl2']//container[@controlname='panel1']/button[@controlname='removeButton']", 30000, null, "b081acc9-d8a3-4a6c-b332-d4538ad31731");
                _cancelbuttonInfo = new RepoItemInfo(this, "CancelButton", "button[@controlname='cancelButton']", 30000, null, "b250c6e1-4071-4bec-82d7-090e233665fd");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("9f200de9-8797-48ef-9f27-56aeb7132e21")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("9f200de9-8797-48ef-9f27-56aeb7132e21")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ActionProviders item.
            /// </summary>
            [RepositoryItem("59284170-fbf3-4877-b284-4500d8843760")]
            public virtual Ranorex.TabPage ActionProviders
            {
                get
                {
                    return _actionprovidersInfo.CreateAdapter<Ranorex.TabPage>(true);
                }
            }

            /// <summary>
            /// The ActionProviders item info.
            /// </summary>
            [RepositoryItemInfo("59284170-fbf3-4877-b284-4500d8843760")]
            public virtual RepoItemInfo ActionProvidersInfo
            {
                get
                {
                    return _actionprovidersInfo;
                }
            }

            /// <summary>
            /// The AddButton item.
            /// </summary>
            [RepositoryItem("966da63c-aba5-403e-8334-8189cf434ae1")]
            public virtual Ranorex.Button AddButton
            {
                get
                {
                    return _addbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The AddButton item info.
            /// </summary>
            [RepositoryItemInfo("966da63c-aba5-403e-8334-8189cf434ae1")]
            public virtual RepoItemInfo AddButtonInfo
            {
                get
                {
                    return _addbuttonInfo;
                }
            }

            /// <summary>
            /// The RemoveButton item.
            /// </summary>
            [RepositoryItem("b081acc9-d8a3-4a6c-b332-d4538ad31731")]
            public virtual Ranorex.Button RemoveButton
            {
                get
                {
                    return _removebuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The RemoveButton item info.
            /// </summary>
            [RepositoryItemInfo("b081acc9-d8a3-4a6c-b332-d4538ad31731")]
            public virtual RepoItemInfo RemoveButtonInfo
            {
                get
                {
                    return _removebuttonInfo;
                }
            }

            /// <summary>
            /// The CancelButton item.
            /// </summary>
            [RepositoryItem("b250c6e1-4071-4bec-82d7-090e233665fd")]
            public virtual Ranorex.Button CancelButton
            {
                get
                {
                    return _cancelbuttonInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The CancelButton item info.
            /// </summary>
            [RepositoryItemInfo("b250c6e1-4071-4bec-82d7-090e233665fd")]
            public virtual RepoItemInfo CancelButtonInfo
            {
                get
                {
                    return _cancelbuttonInfo;
                }
            }
        }

        /// <summary>
        /// The AddActionProviderWizardAppFolder folder.
        /// </summary>
        [RepositoryFolder("1f8437ee-6cf0-4549-a719-df087fa545cf")]
        public partial class AddActionProviderWizardAppFolder : RepoGenBaseFolder
        {
            AutomationSQLdmRepositoryFolders.WizardFramework1Folder _wizardframework1;
            RepoItemInfo _xb0664f16ddb81b92Info;
            RepoItemInfo _wizardframeworkInfo;

            /// <summary>
            /// Creates a new AddActionProviderWizard  folder.
            /// </summary>
            public AddActionProviderWizardAppFolder(RepoGenBaseFolder parentFolder) :
                    base("AddActionProviderWizard", "/form[@controlname='AddActionProviderWizard']", parentFolder, 30000, null, true, "1f8437ee-6cf0-4549-a719-df087fa545cf", "")
            {
                _wizardframework1 = new AutomationSQLdmRepositoryFolders.WizardFramework1Folder(this);
                _xb0664f16ddb81b92Info = new RepoItemInfo(this, "Xb0664f16ddb81b92", "?/?/button[@controlname='xb0664f16ddb81b92']", 30000, null, "c186a7f2-0e8e-4656-831a-fbd4c8991997");
                _wizardframeworkInfo = new RepoItemInfo(this, "WizardFramework", "container[@controlname='wizardFramework']", 30000, null, "eb24f369-be4b-4b23-8e30-81bd4a2ef554");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("1f8437ee-6cf0-4549-a719-df087fa545cf")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("1f8437ee-6cf0-4549-a719-df087fa545cf")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Xb0664f16ddb81b92 item.
            /// </summary>
            [RepositoryItem("c186a7f2-0e8e-4656-831a-fbd4c8991997")]
            public virtual Ranorex.Button Xb0664f16ddb81b92
            {
                get
                {
                    return _xb0664f16ddb81b92Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Xb0664f16ddb81b92 item info.
            /// </summary>
            [RepositoryItemInfo("c186a7f2-0e8e-4656-831a-fbd4c8991997")]
            public virtual RepoItemInfo Xb0664f16ddb81b92Info
            {
                get
                {
                    return _xb0664f16ddb81b92Info;
                }
            }

            /// <summary>
            /// The WizardFramework item.
            /// </summary>
            [RepositoryItem("eb24f369-be4b-4b23-8e30-81bd4a2ef554")]
            public virtual Ranorex.Container WizardFramework
            {
                get
                {
                    return _wizardframeworkInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The WizardFramework item info.
            /// </summary>
            [RepositoryItemInfo("eb24f369-be4b-4b23-8e30-81bd4a2ef554")]
            public virtual RepoItemInfo WizardFrameworkInfo
            {
                get
                {
                    return _wizardframeworkInfo;
                }
            }

            /// <summary>
            /// The WizardFramework1 folder.
            /// </summary>
            [RepositoryFolder("322f9f6e-e971-4cd1-877c-40e24006df4c")]
            public virtual AutomationSQLdmRepositoryFolders.WizardFramework1Folder WizardFramework1
            {
                get { return _wizardframework1; }
            }
        }

        /// <summary>
        /// The WizardFramework1Folder folder.
        /// </summary>
        [RepositoryFolder("322f9f6e-e971-4cd1-877c-40e24006df4c")]
        public partial class WizardFramework1Folder : RepoGenBaseFolder
        {
            RepoItemInfo _comboboxInfo;
            RepoItemInfo _textInfo;
            RepoItemInfo _text1Info;

            /// <summary>
            /// Creates a new WizardFramework1  folder.
            /// </summary>
            public WizardFramework1Folder(RepoGenBaseFolder parentFolder) :
                    base("WizardFramework1", "container[@controlname='wizardFramework']", parentFolder, 30000, null, false, "322f9f6e-e971-4cd1-877c-40e24006df4c", "")
            {
                _comboboxInfo = new RepoItemInfo(this, "ComboBox", ".//combobox[@accessiblename='Provider Name:']/combobox[@accessiblerole='ComboBox']", 30000, null, "1c718fad-674d-4520-9805-63d5195b8842");
                _textInfo = new RepoItemInfo(this, "Text", "element[@controlname='chooseProviderTypePage']//text[@accessiblerole='Text']", 30000, null, "68a5af50-aab0-417c-b254-27d5e44c69f1");
                _text1Info = new RepoItemInfo(this, "Text1", "element[@controlname='smtpConfig']//text[@controlname='fromAddress']/text[@accessiblerole='Text']", 30000, null, "09927d02-6064-493d-8d18-ad9e6aeac963");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("322f9f6e-e971-4cd1-877c-40e24006df4c")]
            public virtual Ranorex.Container Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Container>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("322f9f6e-e971-4cd1-877c-40e24006df4c")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The ComboBox item.
            /// </summary>
            [RepositoryItem("1c718fad-674d-4520-9805-63d5195b8842")]
            public virtual Ranorex.ComboBox ComboBox
            {
                get
                {
                    return _comboboxInfo.CreateAdapter<Ranorex.ComboBox>(true);
                }
            }

            /// <summary>
            /// The ComboBox item info.
            /// </summary>
            [RepositoryItemInfo("1c718fad-674d-4520-9805-63d5195b8842")]
            public virtual RepoItemInfo ComboBoxInfo
            {
                get
                {
                    return _comboboxInfo;
                }
            }

            /// <summary>
            /// The Text item.
            /// </summary>
            [RepositoryItem("68a5af50-aab0-417c-b254-27d5e44c69f1")]
            public virtual Ranorex.Text Text
            {
                get
                {
                    return _textInfo.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text item info.
            /// </summary>
            [RepositoryItemInfo("68a5af50-aab0-417c-b254-27d5e44c69f1")]
            public virtual RepoItemInfo TextInfo
            {
                get
                {
                    return _textInfo;
                }
            }

            /// <summary>
            /// The Text1 item.
            /// </summary>
            [RepositoryItem("09927d02-6064-493d-8d18-ad9e6aeac963")]
            public virtual Ranorex.Text Text1
            {
                get
                {
                    return _text1Info.CreateAdapter<Ranorex.Text>(true);
                }
            }

            /// <summary>
            /// The Text1 item info.
            /// </summary>
            [RepositoryItemInfo("09927d02-6064-493d-8d18-ad9e6aeac963")]
            public virtual RepoItemInfo Text1Info
            {
                get
                {
                    return _text1Info;
                }
            }
        }

        /// <summary>
        /// The SQLdmDesktopClientAppFolder folder.
        /// </summary>
        [RepositoryFolder("19f8a4a0-de98-4d04-8302-0fd75c348780")]
        public partial class SQLdmDesktopClientAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _simplemailtransferprotocolsmtpInfo;

            /// <summary>
            /// Creates a new SQLdmDesktopClient  folder.
            /// </summary>
            public SQLdmDesktopClientAppFolder(RepoGenBaseFolder parentFolder) :
                    base("SQLdmDesktopClient", "/form[@title='']", parentFolder, 30000, null, true, "19f8a4a0-de98-4d04-8302-0fd75c348780", "")
            {
                _simplemailtransferprotocolsmtpInfo = new RepoItemInfo(this, "SimpleMailTransferProtocolSMTP", "?/?/list[@accessiblename='< Select provider type >']/listitem[@accessiblename~'^Simple\\ Mail\\ Transfer\\ Prot']", 30000, null, "5693eda6-2e55-4570-aaab-670cb07e15d2");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("19f8a4a0-de98-4d04-8302-0fd75c348780")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("19f8a4a0-de98-4d04-8302-0fd75c348780")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The SimpleMailTransferProtocolSMTP item.
            /// </summary>
            [RepositoryItem("5693eda6-2e55-4570-aaab-670cb07e15d2")]
            public virtual Ranorex.ListItem SimpleMailTransferProtocolSMTP
            {
                get
                {
                    return _simplemailtransferprotocolsmtpInfo.CreateAdapter<Ranorex.ListItem>(true);
                }
            }

            /// <summary>
            /// The SimpleMailTransferProtocolSMTP item info.
            /// </summary>
            [RepositoryItemInfo("5693eda6-2e55-4570-aaab-670cb07e15d2")]
            public virtual RepoItemInfo SimpleMailTransferProtocolSMTPInfo
            {
                get
                {
                    return _simplemailtransferprotocolsmtpInfo;
                }
            }
        }

        /// <summary>
        /// The IderaSQLDiagnosticManagerSQLdmRepoAppFolder folder.
        /// </summary>
        [RepositoryFolder("02e2bddb-96ad-4da9-bf49-406cf03d0b37")]
        public partial class IderaSQLDiagnosticManagerSQLdmRepoAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _twitterInfo;

            /// <summary>
            /// Creates a new IderaSQLDiagnosticManagerSQLdmRepo  folder.
            /// </summary>
            public IderaSQLDiagnosticManagerSQLdmRepoAppFolder(RepoGenBaseFolder parentFolder) :
                    base("IderaSQLDiagnosticManagerSQLdmRepo", "/form[@title~'^Idera\\ SQL\\ diagnostic\\ mana']", parentFolder, 30000, null, true, "02e2bddb-96ad-4da9-bf49-406cf03d0b37", "")
            {
                _twitterInfo = new RepoItemInfo(this, "Twitter", "statusbar[@automationid='statusBar']/?/?/container[@automationid='viewContainer']/container[@automationid='windowsFormsHostControl']/?/?/container[@controlname='_child']//container[@controlname='panel8']/link[@controlname='_twitterLinkLabel']/?/?/link[@accessiblename='Twitter']", 30000, null, "56ecba9a-d8b1-416b-93d7-dbb379964d32");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("02e2bddb-96ad-4da9-bf49-406cf03d0b37")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("02e2bddb-96ad-4da9-bf49-406cf03d0b37")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Twitter item.
            /// </summary>
            [RepositoryItem("56ecba9a-d8b1-416b-93d7-dbb379964d32")]
            public virtual Ranorex.Link Twitter
            {
                get
                {
                    return _twitterInfo.CreateAdapter<Ranorex.Link>(true);
                }
            }

            /// <summary>
            /// The Twitter item info.
            /// </summary>
            [RepositoryItemInfo("56ecba9a-d8b1-416b-93d7-dbb379964d32")]
            public virtual RepoItemInfo TwitterInfo
            {
                get
                {
                    return _twitterInfo;
                }
            }
        }

        /// <summary>
        /// The ExceptionMessageBoxFormAppFolder folder.
        /// </summary>
        [RepositoryFolder("a6f6ed3c-e133-491f-83e7-43a77aec91a2")]
        public partial class ExceptionMessageBoxFormAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _button1Info;

            /// <summary>
            /// Creates a new ExceptionMessageBoxForm  folder.
            /// </summary>
            public ExceptionMessageBoxFormAppFolder(RepoGenBaseFolder parentFolder) :
                    base("ExceptionMessageBoxForm", "/form[@controlname='ExceptionMessageBoxForm']", parentFolder, 30000, null, true, "a6f6ed3c-e133-491f-83e7-43a77aec91a2", "")
            {
                _button1Info = new RepoItemInfo(this, "Button1", "container[@controlname='pnlForm']/?/?/button[@controlname='button1']", 30000, null, "8d334b4d-61f9-43f8-94c6-9f8d4062b915");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("a6f6ed3c-e133-491f-83e7-43a77aec91a2")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("a6f6ed3c-e133-491f-83e7-43a77aec91a2")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Button1 item.
            /// </summary>
            [RepositoryItem("8d334b4d-61f9-43f8-94c6-9f8d4062b915")]
            public virtual Ranorex.Button Button1
            {
                get
                {
                    return _button1Info.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Button1 item info.
            /// </summary>
            [RepositoryItemInfo("8d334b4d-61f9-43f8-94c6-9f8d4062b915")]
            public virtual RepoItemInfo Button1Info
            {
                get
                {
                    return _button1Info;
                }
            }
        }

    }
#pragma warning restore 0436
}